POST http://localhost:3000/customer/register-customer
Content-Type: application/json
    {
    "nombre": "María García López",
    "email": "maria.garcia@email.com",
    "telefono": "3201234567"
    }

GET http://localhost:3000/customer/get-customer-info/1

GET http://localhost:3000/customer/get-customer-by-email/maria.garcia@email.com

PUT http://localhost:3000/customer/update-customer-info/1
Content-Type: application/json
    {
    "nombre": "María García Rodríguez",
    "email": "maria.rodriguez@email.com",
    "telefono": "3209876543"
    }

